# Generated by Django 2.2.14 on 2020-09-30 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adai_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='selector', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_lastname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Materias')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=128)),
                ('esCorrecto', models.BooleanField()),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Estudiante')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Curso')),
                ('historico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Historico')),
                ('materias_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Materias')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ejercicio', models.IntegerField()),
                ('tema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Tema')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EjercicioExamenInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Ejercicio')),
                ('examen_inicial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.ExamenInicial')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Ejercicio')),
                ('examen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Examen')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('elemento', models.CharField(max_length=255)),
                ('tema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adai_api.Tema')),
            ],
        ),
    ]
