# Generated by Django 2.2.14 on 2020-07-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adai_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_test',
            new_name='status_text',
        ),
    ]
