# Generated by Django 2.2.14 on 2020-07-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adai_api', '0004_auto_20200729_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
