# Generated by Django 2.2.14 on 2020-08-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adai_api', '0006_auto_20200730_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
            ],
        ),
    ]
