# Generated by Django 2.2.14 on 2020-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adai_api', '0007_examenfinal_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_id', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('elemento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_id', models.IntegerField()),
                ('nota', models.FloatField()),
                ('cantidad_ejercicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamenInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField()),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_id', models.IntegerField()),
                ('alumno_id', models.IntegerField()),
                ('materias_id', models.IntegerField()),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Practico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
                ('cantidad_ejercicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.IntegerField()),
                ('examen_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasExamenInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.IntegerField()),
                ('examen_inicial_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasPractico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.IntegerField()),
                ('practica_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExamenFinal',
        ),
        migrations.AddField(
            model_name='historico',
            name='alumno_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
